[programs.localnet]
messengerapp = "G1t9GTHG5q5MLtSbU5JAxsZAevDsQVeQ7kY55wAdrNAP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/putin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
